### ISSUE TITLE
Error Building on Cloudflare

### ISSUE THREAD

**Issue by peio72** [nuxt-modules/leaflet#10]
Got the following error trying to build and deploy on Cloudflare

17:51:25.688 | [info] [nitro] Building Nuxt Nitro server (preset: `cloudflare-pages`)
-- | --
17:51:29.265 | [error] [nitro] RollupError: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
17:51:29.265 |  
17:51:29.265 |  
17:51:29.265 | 1: �PNG
17:51:29.265 | ^
17:51:29.265 | 2: 
17:51:29.266 | 3:  IHDR)�����IDATx�W�cY�څ����i�k�޶L��c�5��dm��x�����f���U�^���=�<'���2��v��nX�0E���h��v* ...
17:51:29.266 | [error] Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
17:51:29.266 | at getRollupEror (node_modules/rollup/dist/es/shared/parseAst.js:375:41)
17:51:29.267 | at ParseError.initialise (node_modules/rollup/dist/es/shared/node-entry.js:11155:28)
17:51:29.267 | at convertNode (node_modules/rollup/dist/es/shared/node-entry.js:12895:10)
17:51:29.267 | at convertProgram (node_modules/rollup/dist/es/shared/node-entry.js:12215:12)
17:51:29.267 | at Module.setSource (node_modules/rollup/dist/es/shared/node-entry.js:14039:24)
17:51:29.268 | at async ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/node-entry.js:18697:13)
17:51:29.268 |  
17:51:29.268 | [error] Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
17:51:29.323 | Failed: Error while executing user command. Exited with error code: 1
17:51:29.334 | Failed: build command exited with code: 1
17:51:30.443 | Failed: error occurred while running build command

</pre><div class="c_tf c_d"></div>

**Comment by Gugustinette** [comment]
Hi !

It seems related to this issue : https://github.com/Gugustinette/Nuxt-Leaflet/issues/9#issuecomment-1936482979

Which was resolved by wrapping the `<LMap>` component in a `<client-only>` component.

```vue
<client-only>
  <LMap ...> </LMap>
</client-only>
```

**Comment by peio72** [comment]
Tried this but still getting the error on cloudflare build

**Comment by Gugustinette** [comment]
How are you rendering your application ? There are different strategies available so make sure to understand how is your code manipulated by Nuxt : https://nuxt.com/docs/guide/concepts/rendering

If you're only getting this error on cloudflare environments, then I won't be able to help you further as the error really doesn't tell much.

**Comment by ricktap** [comment]
Hi,

had the same issue.
Install @rollup/plugin-image

```bash
yarn add -D @rollup/plugin-image
```

and add this to your nuxt.config.js:

```node
export default defineNuxtConfig({
  nitro: {
      preset: 'cloudflare-pages',
      rollupConfig: {
        plugins: [
            image()
        ]
      }
    },
    // ...
});
```

rollup does not know how to handle png files without this plugin.

Took me an hour or two to find out that I needed to lookup the nitro documentation...
https://nitro.unjs.io/config#rollupconfig

**Comment by Gugustinette** [comment]
So this is required to make Nuxt Leaflet work on Cloudflare ?

I'll do some testing and document it, thanks !

**Comment by ricktap** [comment]
As far as I understood, this is more of a nitro requirement. So this could also apply to netlify, vercel, amplify, github pages, ... deployments that use the nitro presets. But I have no experience with those providers, so I can't tell you, if their presets come with image handling out of the box - but I kind of doubt it.

I'm 100% positive though, that this (or an equivalent) plugin is necessary to tell nitro/rollup how to handle the png import statements in the next leaflet library.

**Comment by egemenozkan** [comment]
Hello,
I'm getting same error.

	[error] [nitro] RollupError: node_modules/leaflet/dist/images/marker-icon-2x.png (1:0): Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
con-2x.png (1:0): Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
21:11:18.384	  at getRollupError (node_modules/rollup/dist/es/shared/parseAst.js:392:41)
21:11:18.384	  at ParseError.initialise (node_modules/rollup/dist/es/shared/node-entry.js:11170:28)
21:11:18.384	  at convertNode (node_modules/rollup/dist/es/shared/node-entry.js:12915:10)
21:11:18.384	  at convertProgram (node_modules/rollup/dist/es/shared/node-entry.js:12232:12)
21:11:18.384	  at Module.setSource (node_modules/rollup/dist/es/shared/node-entry.js:14076:24)
21:11:18.384	  at async ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/node-entry.js:18729:13) 
21:11:18.384	
21:11:18.384	[error] node_modules/leaflet/dist/images/marker-icon-2x.png (1:0): Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
21:11:18.504	Failed: Error while executing user command. Exited with error code: 1
21:11:18.515	Failed: build command exited with code: 1
21:11:19.898	Failed: error occurred while running build command

**Comment by Gugustinette** [comment]
> Hello,
> I'm getting same error.
> 
> 	[error] [nitro] RollupError: node_modules/leaflet/dist/images/marker-icon-2x.png (1:0): Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
> con-2x.png (1:0): Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
> 21:11:18.384	  at getRollupError (node_modules/rollup/dist/es/shared/parseAst.js:392:41)
> 21:11:18.384	  at ParseError.initialise (node_modules/rollup/dist/es/shared/node-entry.js:11170:28)
> 21:11:18.384	  at convertNode (node_modules/rollup/dist/es/shared/node-entry.js:12915:10)
> 21:11:18.384	  at convertProgram (node_modules/rollup/dist/es/shared/node-entry.js:12232:12)
> 21:11:18.384	  at Module.setSource (node_modules/rollup/dist/es/shared/node-entry.js:14076:24)
> 21:11:18.384	  at async ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/node-entry.js:18729:13) 
> 21:11:18.384	
> 21:11:18.384	[error] node_modules/leaflet/dist/images/marker-icon-2x.png (1:0): Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
> 21:11:18.504	Failed: Error while executing user command. Exited with error code: 1
> 21:11:18.515	Failed: build command exited with code: 1
> 21:11:19.898	Failed: error occurred while running build command

So you tried the previous fix with @rollup/plugin-image and still getting the error ?

**Comment by Gugustinette** [comment]
For now, we'll keep this as the correct answer :

- Install `@rollup/plugin-image`
```bash
npm install @rollup/plugin-image
```
- Configure the plugin in your `nuxt.config.ts` file
```typescript
import { image } from '@rollup/plugin-image'

export default defineNuxtConfig({
  nitro: {
      preset: 'cloudflare-pages',
      rollupConfig: {
        plugins: [
            image()
        ]
      }
    }
});
```

Do not hesitate to re-open the issue if it keeps happening even with the fix.
