### ISSUE TITLE
Add support for Leaflet.heat

### ISSUE THREAD

**Issue by Gugustinette** [nuxt-modules/leaflet#16]
We should support [Leaflet.heat](https://github.com/Leaflet/Leaflet.heat).

Either by documenting a way to use the plugin (similar to [Leaflet.draw documentation](https://gugustinette.github.io/Nuxt-Leaflet/guide/leaflet-draw.html)) or providing Vue components.

**Comment by KazBrekker1** [comment]
Any progress in with this integration?
Really looking forward for it.

**Comment by Gugustinette** [comment]
@KazBrekker1 This is the next integration coming 👍

**Comment by Gugustinette** [comment]
@KazBrekker1 This is available in latest version : [v1.2.0](https://github.com/nuxt-modules/leaflet/releases/tag/1.2.0)
