### ISSUE TITLE
Docs: LIcon demo uses global style instead of scoped

### ISSUE THREAD

**Issue by MarcelRiedeman** [nuxt-modules/leaflet#23]
On the [demo](https://gugustinette.github.io/Nuxt-Leaflet/components/l-icon.html#demo) of `LIcon`, a global `<style>` is used instead of a `<style scoped>`. As a result, you change every icon's style in the whole project, which can lead to nasty bugs when you want to style a different icon elsewhere.

Simply putting `scoped` doesn't work, because `leaflet-div-icon` is a class of a child component. I already tried using [Vue's child selector](https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements), but that didn't work.

**Comment by Gugustinette** [comment]
You should be able to add a `class-name` attribute to your `<LIcon />` as follow :
```vue
<LIcon class-name="my-icons">Hello, Map!</LIcon>
```
```css
.my-icons {
  ...
}
```

Doesn't this work ?
This is not very clear in the documentation so I might change that.

**Comment by Gugustinette** [comment]
Closing this as no update was made, feel free to re-open this as needed.
